# These entries are for the minimum amount of luck required for the event to actually trigger.
# These work in addition to the RNG generator,
#     meaning both the RNG and this condition must be met for the event to trigger.
# These values must be in the form of doubles, as listed below.
# The maximum amount of luck that can be attributed is 1024.0, and the minimum is -1024.0

high_rarity_chance: 512.0
medium_rarity_chance: 128.0
low_rarity_chance: 64.0

# Change whether verbosity is enabled globally or not.
# If the verbosity is set to true, then all players will have the option to turn it off for themselves only.
# If the verbosity is set to false, then players will not have the option to turn it on.
global_verbosity: true

# The following entries are for the rarity level of each event trigger.
# This will determine which rarity chance to use which ensures players
# The following values are accepted: NONE, LOW, MED, HIGH
#- None implies that there is no rarity chance attributed to that feature.
# These entries are case-sensitive.

block_drops: LOW
bone_meal: MED
cheat_death: MED
enchanting: HIGH
experience: HIGH
give_damage: LOW
hide_check: MED
item_drops: LOW
jump_boost: MED
ore_vein: HIGH
random_effect: HIGH
restore_hunger: NONE
take_damage: MED
unbreakable: HIGH

# This section is for Database storage.
# If you wish to use a database, you must fill out the following information.

#database_types: MYSQL, SQLITE, REDIS, NONE
database_type: NONE

# MySQL Database
mysql:
  host: localhost
  port: 3306
  database: minecraft
  username: root
  password: password

# SQLite Database
sqlite:
  path: database.db

# Redis Database
redis:
  host: localhost
  port: 6379
  password: password
  database: 0
